# Generated by Django 2.1.1 on 2018-11-06 17:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20181106_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 6, 17, 28, 10, 559700, tzinfo=utc)),
        ),
    ]
